name: HelloWorld
options:
  bundleIdPrefix: com.myhello.app
  objectVersion: 56
targets:
  HelloWorld:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - HelloWorld
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.myhello.app.HelloWorld
        INFOPLIST_FILE: HelloWorld/Info.plist
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
