name: HelloWorld
options:
  bundleIdPrefix: com.myhello.app
  objectVersion: 56
  deploymentTarget:
    iOS: "15.0"
targets:
  HelloWorld:
    type: application
    platform: iOS
    sources:
      - HelloWorld
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.myhello.app.HelloWorld
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
